{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_ALLRequests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(request_GETRequests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_POSTRequests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_DELETERequests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_PUTRequests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "user_ActiveUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_goodAuths{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_badAuths{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(purchase_pizzasSoldCount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "purchase_failedPizzasCount{source=\"jwt-pizza-service\"}",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpuUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "latency_requestTime{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(purchase_totalRevenue{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Pizza Purchases"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "latency_PizzaCreationTime{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  }
 ]
}